version: "3.8"
services:
  account:
      build:
        context: ./Account
        dockerfile: Dockerfile
      restart: on-failure
      networks:
        - fakegram
      ports:
        - 8080:8080
      environment:
        KAFKA_SERVER: ${KAFKA_SERVER:-kafka:9094}
        JWT_SECRET: ${JWT_SECRET:-secret}
        CASSANDRA_POINT: ${CASSANDRA_POINT:-cassandra:9042}
      depends_on: 
        - kafka
        - cassandra
  cassandra:
      image: djokicm/fakegram-cassandra:0.0.1
      restart: on-failure
      networks:
        - fakegram
      ports:
        - 9042:9042
  zookeeper:
      image: confluentinc/cp-zookeeper:6.2.0
      networks:
        - fakegram
      ports:
        - 2181:2181
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
      image: confluentinc/cp-kafka:6.2.0
      networks:
        - fakegram
      ports: 
        - 9092:9092
      environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENERS: PLAINTEXT://kafka:9094,OUTSIDE://kafka:9092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9094,OUTSIDE://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      depends_on: 
        - zookeeper
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: on-failure
    networks:
      - fakegram
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alert-manager
    restart: on-failure
    networks:
        - fakegram
    ports:
      - 9093:9093
    volumes:
        - ./alert_manager:/etc/alermanager
  node-exporter:
    image: prom/node-exporter:v1.1.2
    container_name: node-exporter
    networks:
      - fakegram
    ports:
      - 9100:9100
  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    networks:
      - fakegram
    ports:
      - 8080:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
networks:
    fakegram:
      name: fakegram
      driver: bridge