{
 "title": "Fakegram Http metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last 24h request count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_request_count[24h]))"
    }
   ]
  },
  {
   "title": "Successful and failed requests count",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_response_count{status=~\"[23].+\"}[24h]))",
     "legendFormat": "Http Status 200/300"
    },
    {
     "expr": "sum(increase(http_response_count{status=~\"[45].+\"}[24h]))",
     "legendFormat": "Http Status 400/500"
    }
   ]
  },
  {
   "title": "Http Traffic in GB",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_traffic_counter) / 1024 / 1024 / 1024"
    }
   ]
  },
  {
   "title": "404 Status Count by Endpoints",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by(endpoint) (increase(http_response_count{status=~\"404\"}[24h]))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Unique visitors",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by(browser, originIp) (http_request_count))"
    }
   ]
  }
 ]
}