global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "rules/recording_rules.yml"
  - "rules/alerting_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "account-service"
    static_configs:
      - targets: ["account:8080"]

  - job_name: "post-service"
    static_configs:
      - targets: ["post-service:8080"]

  - job_name: "agent-service"
    static_configs:
      - targets: ["agent-service:8080"]

  - job_name: "admin-service"
    static_configs:
      - targets: ["admin-service:8080"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
